[program:web]
command=/opt/matlog/backend/.venv/bin/gunicorn --workers 4 --bind unix:/opt/matlog/backend/app.sock config.wsgi:application
directory=/opt/matlog/backend/
user=root
autostart=true
autorestart=true
redirect_stderr=true
environment=DJANGO_SETTINGS_MODULE="matlog.settings"
stdout_logfile=/var/log/software/django.log
