# Generated by Django 5.2.7 on 2025-11-14 12:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("materials", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="material",
            name="order",
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
