upstream backend {
  server unix:/opt/matlog/backend/app.sock;
}

server {
  server_name matlog.vladyslav.top

  keepalive_timeout 300;
  client_max_body_size 300M;

  location = /favicon.ico {access_log off; log_not_found off;}
  index index.html;
  root /opt/matlog/frontend/dist/;

  location /static {
    alias /opt/matlog/backend/static;
  }

  location /api {
    proxy_pass http://backend;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header Host $http_host;
    proxy_redirect off;
    proxy_hide_header X-Frame-Options;
  }
  location /admin {
    proxy_pass http://backend;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header Host $http_host;
    proxy_redirect off;
    proxy_hide_header X-Frame-Options;
  }

  location / {
    try_files $uri /index.html = 404;
  }
}
