# Generated by Django 5.2.7 on 2025-11-14 11:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="theme",
            name="course",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="themes",
                to="courses.course",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="theme",
            name="name",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterUniqueTogether(
            name="theme",
            unique_together={("name", "course")},
        ),
    ]
